#!/usr/bin/env python3
"""
Create the IEEE Transactions on Instrumentation and Measurement (TIM)
manuscript (.docx) — English version.

All numerical results are read from results/summary.json (generated by
src/simulate.py, src/real_waveforms.py and src/analyze.py); none are
hard-coded here. References are numbered in order of first appearance by
the Citations manager.

IEEE TIM requires figures and tables to be embedded in the manuscript
file near their first citation. Each equation is written as a Word-native
Office Math Markup Language (OMML) object produced from LaTeX by pandoc.
"""

import os
import re
import subprocess
import sys
import tempfile
import zipfile

from docx import Document
from docx.shared import Pt, Cm, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from lxml import etree

from manuscript_common import REFDB, Citations, load_summary

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(SCRIPT_DIR, "..", "src")
sys.path.insert(0, SRC)
import real_waveforms as RW
OUTDIR = os.path.join(SCRIPT_DIR, "..", "manuscripts")
OUTPATH = os.path.join(OUTDIR, "TIM_ZeroFree_Manuscript_EN.docx")
os.makedirs(OUTDIR, exist_ok=True)

S = load_summary()
C = Citations(REFDB)
P = S["parameters"]
st = S["static"]
dy = S["dynamic"]
rg = S["range_dependence"]
rst = S.get("real_static", {})


# ---------- number formatting helpers (values come from summary.json) ------
def f2(x):
    return f"{x:.2f}"


def f1(x):
    return f"{x:.1f}"


def f3(x):
    return f"{x:.3f}"


def ci(lo, hi, nd=3):
    return f"{lo:.{nd}f} to {hi:.{nd}f}"


def signed(x, nd=1):
    return f"{x:+.{nd}f}"


# ---------- docx setup ----------
def set_section_columns(section, num=2, space="720"):
    """Set the number of columns for a section (IEEE Transactions layout)."""
    sectPr = section._sectPr
    cols = sectPr.xpath("./w:cols")
    if cols:
        cols[0].set(qn("w:num"), str(num))
        cols[0].set(qn("w:space"), space)
    else:
        cols_el = OxmlElement("w:cols")
        cols_el.set(qn("w:num"), str(num))
        cols_el.set(qn("w:space"), space)
        sectPr.append(cols_el)


doc = Document()
# IEEE Transactions on Instrumentation and Measurement uses U.S. Letter
# (8.5 x 11 in) with 0.75-inch margins and a two-column body.
for section in doc.sections:
    section.top_margin = Cm(1.91)
    section.bottom_margin = Cm(1.91)
    section.left_margin = Cm(1.91)
    section.right_margin = Cm(1.91)
    set_section_columns(section, 1)  # title page is single column

style = doc.styles["Normal"]
style.font.name = "Times New Roman"
style.font.size = Pt(10)
style.paragraph_format.line_spacing = 1.15
style.paragraph_format.space_after = Pt(0)


def latex_to_omml(latex, display=False):
    """Return a Word OMML element for a LaTeX expression via pandoc."""
    wrap = f"$${latex}$$" if display else f"${latex}$"
    with tempfile.TemporaryDirectory() as td:
        md_path = os.path.join(td, "eq.md")
        docx_path = os.path.join(td, "eq.docx")
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(wrap)
        subprocess.run(["pandoc", md_path, "-o", docx_path],
                       check=True, stdout=subprocess.DEVNULL)
        with zipfile.ZipFile(docx_path) as z:
            xml = z.read("word/document.xml")
    tree = etree.fromstring(xml)
    ns = {"m": "http://schemas.openxmlformats.org/officeDocument/2006/math"}
    omath = tree.xpath(".//m:oMath", namespaces=ns)[0]
    return etree.fromstring(etree.tostring(omath))


def add_math_run(p, latex, font_size=Pt(12)):
    run = p.add_run()
    run.font.name = "Cambria Math"
    run.font.size = font_size
    run._r.append(latex_to_omml(latex))
    return run


EQ_NUM = 0


def add_eq(latex):
    """Insert a numbered display equation (centered, number flush right)."""
    global EQ_NUM
    EQ_NUM += 1
    # Use a borderless two-cell table so the equation and number are on
    # the same line and fit within a single column in two-column mode.
    tbl = doc.add_table(rows=1, cols=2)
    tbl.autofit = False
    tbl.allow_autofit = False
    tbl.columns[0].width = Inches(2.5)
    tbl.columns[1].width = Inches(0.7)
    # left cell: equation, centered
    cell = tbl.rows[0].cells[0]
    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(3)
    add_math_run(p, latex, font_size=Pt(10))
    # right cell: equation number
    cell = tbl.rows[0].cells[1]
    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    p.paragraph_format.space_after = Pt(3)
    run = p.add_run(f"({EQ_NUM})")
    run.font.name = "Times New Roman"
    run.font.size = Pt(10)
    # remove table borders
    tblPr = tbl._tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "bottom", "left", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "none")
        borders.append(el)
    tblPr.append(borders)


def add_para_with_refs(text, bold=False, italic=False, alignment=None,
                       space_after=Pt(6), font_size=Pt(10)):
    p = doc.add_paragraph()
    if alignment:
        p.alignment = alignment
    p.paragraph_format.space_after = space_after
    for part in re.split(r"(\{[^}]+\}|\$[^$]+\$)", text):
        if part.startswith("{") and part.endswith("}"):
            run = p.add_run("[" + part[1:-1] + "]")
            run.font.name = "Times New Roman"
            run.font.size = font_size
            run.bold = bold
            run.italic = italic
        elif part.startswith("$") and part.endswith("$"):
            run = p.add_run()
            run.font.name = "Cambria Math"
            run.font.size = font_size
            if bold:
                run.bold = True
            if italic:
                run.italic = True
            run._r.append(latex_to_omml(part[1:-1]))
        else:
            run = p.add_run(part)
            run.font.name = "Times New Roman"
            run.font.size = font_size
            run.bold = bold
            run.italic = italic
    return p


def add_para(text, bold=False, italic=False, alignment=None, space_after=Pt(6)):
    return add_para_with_refs(text, bold, italic, alignment, space_after)


def add_heading_styled(text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.name = "Times New Roman"
        run.font.color.rgb = RGBColor(0, 0, 0)
    return h


# IEEE TIM requires figures inline near their first citation. The first time a
# figure is cited in the body it is inserted immediately after that paragraph.
FIG_STEMS = [
    "figure1_signal_decomposition",
    "figure2_scenarios_concordance",
    "figure3_detection_panel",
    "figure4_ba_masked_gain",
    "figure5_dynamic_response",
    "figure6_range_dependence",
    "figure7_real_validation",
]
FIGURE_NUM = 0
DATA_TABLES = []


def next_fig_num():
    """Return the number of the next figure to be inserted (for in-text cites)."""
    return FIGURE_NUM + 1


def add_figure(caption):
    """Insert the next figure inline and add its caption."""
    global FIGURE_NUM
    stem = FIG_STEMS[FIGURE_NUM]
    FIGURE_NUM += 1
    fig_path = os.path.join(SCRIPT_DIR, "..", "figures", f"{stem}.png")
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(3)
    run = p.add_run()
    if os.path.exists(fig_path):
        # Figure width is set to one IEEE column (≈3.25 in)
        run.add_picture(fig_path, width=Inches(3.25))
    cap = add_para_with_refs(f"Fig. {FIGURE_NUM}. {caption}",
                              italic=True,
                              alignment=WD_ALIGN_PARAGRAPH.CENTER,
                              space_after=Pt(12),
                              font_size=Pt(9))
    return FIGURE_NUM



def horizontal_borders(table):
    """Apply horizontal rules only (TIM style: no vertical rules)."""
    tblPr = table._tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "bottom", "insideH"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "single")
        el.set(qn("w:sz"), "4")
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "000000")
        borders.append(el)
    for edge in ("left", "right", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "none")
        borders.append(el)
    tblPr.append(borders)


def set_table_width(table, width_in=3.25):
    """Set total table width and distribute columns evenly (two-column friendly)."""
    table.autofit = False
    tblPr = table._tbl.tblPr
    # remove any existing tblW to avoid duplicate/overriding width specs
    for existing in tblPr.findall(qn("w:tblW")):
        tblPr.remove(existing)
    tblW = OxmlElement("w:tblW")
    tblW.set(qn("w:type"), "dxa")
    tblW.set(qn("w:w"), str(int(width_in * 1440)))
    tblPr.append(tblW)
    n_cols = len(table.columns)
    col_w = width_in / n_cols
    for col in table.columns:
        col.width = Inches(col_w)
    # also fix the cell widths in the first row so Word respects them
    for cell in table.rows[0].cells:
        tcPr = cell._tc.get_or_add_tcPr()
        for existing in tcPr.findall(qn("w:tcW")):
            tcPr.remove(existing)
        tcW = OxmlElement("w:tcW")
        tcW.set(qn("w:type"), "dxa")
        tcW.set(qn("w:w"), str(int(col_w * 1440)))
        tcPr.append(tcW)


# ══════════════════════════════════════════════════════════════════
# TITLE PAGE (single column)
# ══════════════════════════════════════════════════════════════════
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
trun = title.add_run(
    "What Zeroing Cannot Fix: Detecting Residual Gain and Dynamic-Response "
    "Errors After Zero Calibration in Invasive Arterial Pressure Monitoring")
trun.font.name = "Times New Roman"
trun.font.size = Pt(16)
trun.bold = True
title.paragraph_format.space_after = Pt(12)

doc.add_paragraph()
add_para("[Author names to be completed]", alignment=WD_ALIGN_PARAGRAPH.CENTER)
add_para("[Affiliations to be completed]", alignment=WD_ALIGN_PARAGRAPH.CENTER)
doc.add_paragraph()
add_para("Corresponding author:", bold=True)
add_para("[Name, address, email, ORCID]")
doc.add_paragraph()
add_para("EDICS: Metrology and Measurement Fundamentals / Measurement and "
         "estimation uncertainty; Medical, Biomedical, and Healthcare "
         "Instrumentation and Measurement / Medical measurements.")
doc.add_paragraph()
add_para("Index Terms\u2014", bold=True, space_after=Pt(0))
kw = doc.paragraphs[-1]
kwr = kw.add_run(
    "Arterial pressure monitoring, zero calibration, concordance correlation "
    "coefficient, Bland\u2013Altman analysis, proportional bias, dynamic "
    "response, fast-flush test, method comparison, measurement uncertainty, "
    "biomedical instrumentation, pressure sensors, sensor calibration")
kwr.font.name = "Times New Roman"
kwr.font.size = Pt(10)
doc.add_paragraph()
doc.add_paragraph()
add_para("Conflicts of Interest and Source of Funding:", bold=True,
         space_after=Pt(0))
add_para("[To be completed by the authors. State each author\u2019s financial, "
         "consultant, institutional and other relationships and all sources "
         "of funding; if there are none, state \u201cnone declared\u201d.]")

# Switch to two-column Transactions body after the title page.
body_section = doc.add_section(WD_SECTION.NEW_PAGE)
set_section_columns(body_section, 2)

# ══════════════════════════════════════════════════════════════════
# ABSTRACT (single paragraph, 150\u2013250 words)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Abstract", level=1)

add_para(
    "Zero calibration removes the direct-current (DC) offset of an invasive "
    "arterial pressure transducer but not the sensor-gain (scale) error or "
    "dynamic-response (damping) distortion. We used seeded simulations ("
    rf"$n = {P['n_static']}$ paired systolic pressures) and VitalDB beat-by-beat "
    "waveforms ("
    rf"$n = {P['n_real_cases']}$ cases, "
    rf"$n = {P['n_real_beats_per_scenario']:,}$ paired beats per scenario) to "
    "test which analyses detect a residual gain error after zeroing. Four "
    "static cases\u2014offset only, ideal zeroing, 10% gain error, and gain "
    "masked by a compensating offset\u2014plus optimal, under-damped and over-"
    "damped systems were assessed with the Bland\u2013Altman summary, "
    "Bland\u2013Altman regression, Deming and Passing\u2013Bablok regression, and "
    "Lin\u2019s concordance correlation coefficient (CCC) with scale shift $v$. "
    "The masked gain produced a mean bias of only "
    rf"{signed(st['S4_gain_masked']['bias'])} mmHg, yet the regression slopes "
    "and CCC scale shift ($v = "
    rf"{f3(st['S4_gain_masked']['v'])}$) detected it. Under-damping inflated "
    f"and over-damping attenuated pulse pressure by "
    f"{round((dy['underdamped_pp']['mean_ratio']-1)*100)}% and "
    f"{round((1-dy['overdamped_pp']['mean_ratio'])*100)}% respectively; these "
    "frequency-dependent gains persist after zeroing and are diagnosed by the "
    "fast-flush test. CCC rose with sampled pressure range ("
    rf"{f2(rg['ccc'][0])} to {f2(rg['ccc'][-1])}), whereas $v$ approached the "
    "true gain ratio. Real waveforms reproduced the masked-gain pattern ("
    rf"{signed(rst['R4_gain_masked']['bias'])} mmHg, "
    rf"$v = {f3(rst['R4_gain_masked']['v'])}$). A mean-bias summary alone can "
    "miss a clinically relevant gain error; reports should add proportional-"
    "bias-aware analyses, the CCC decomposition with pressure range, a dynamic-"
    "response check, and define $v \\approx 1$ without calibration as a design "
    "target for self-calibrating sensors.")

# ══════════════════════════════════════════════════════════════════
# 1. INTRODUCTION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("1. Introduction", level=1)

add_para_with_refs(
    "Accurate pressure measurement is a central problem in biomedical "
    "instrumentation and measurement. Invasive arterial blood pressure (ABP) "
    "monitoring, performed millions of times peri-operatively and in critical "
    "care, links a pressure transducer, a fluid-filled catheter system and a "
    "calibration protocol that defines atmospheric pressure as the zero "
    "reference " + C.cite("aami1994", "shirmohammadi2016") + ". The first "
    "part of that protocol, zeroing, removes the direct-current (DC) offset "
    "created by the hydrostatic column, the gauge-pressure reference and slow "
    "drift; clinicians zero before monitoring "
    + C.cite("saugel2020", "saugelsessler2021") + " and repeat whenever the "
    "height relationship between transducer and catheter changes "
    + C.cite("gupta2025") + ". What zeroing cannot do is verify the sensor "
    "gain (sensitivity), i.e. the scale factor that converts a true pressure "
    "change into the displayed value " + C.cite("mark1998", "mcghee2002") +
    ". If the gain is wrong, the waveform is scaled and the error persists "
    "after zeroing. Our first question is therefore whether, after correct "
    "zeroing, a residual gain (scale) error can remain undetected.")

add_para_with_refs(
    "A second, frequency-dependent gain error arises from the dynamic response "
    "of the catheter\u2013transducer system. Under- or over-damping distorts "
    "the pulsatile signal and therefore pulse pressure "
    + C.cite("gardner1981") + ". This pulsatile gain error also survives "
    "zeroing and, unlike a static scale error, varies with heart rate; our "
    "second question is how it behaves and how it should be checked at the "
    "bedside.")

add_para_with_refs(
    "How agreement is judged is the third issue. Validation studies for ABP "
    "and derived haemodynamic monitors overwhelmingly report the Bland\u2013"
    "Altman summary (mean bias and 95% limits of agreement) "
    + C.cite("blandaltman1986") + " and the Critchley percentage error "
    + C.cite("critchley1999") + ", with attention to the precision of the "
    "reference method " + C.cite("cecconi2009") + ". In practice, "
    "clinicians and manufacturers often read this minimal summary as a "
    "complete statement of agreement. Yet the original Bland\u2013Altman "
    "method also includes regression of the differences on the mean to "
    "detect proportional bias " + C.cite("blandaltman1999") + ", a step "
    "that is frequently omitted; when an offset and a gain error partially "
    "cancel, the mean-bias summary alone is misleading. Using a reproducible "
    "simulation, and without claiming that gain error is invisible to a "
    "properly conducted Bland\u2013Altman analysis, we ask which analyses "
    "actually reported in the literature detect a residual gain error after "
    "zeroing, and we position Lin\u2019s concordance correlation coefficient "
    "(CCC) and its scale-shift component " + C.cite("lin1989", "lin2000") +
    ", together with Deming " + C.cite("linnet1990") + " and Passing\u2013"
    "Bablok " + C.cite("passingbablok1983") + " regression, as "
    "complementary diagnostics, noting that the CCC depends on the sampled "
    "pressure range " + C.cite("nickerson1997", "barnhart2007") + ".")

add_para_with_refs(
    "These choices matter beyond the individual study. Regulatory evaluation "
    "of a new monitor rests on the same method-comparison statistics, so if "
    "the reported summary cannot separate offset-corrected agreement from "
    "genuine gain accuracy, the approval decision inherits that blind spot. "
    "We therefore use the simulation to define a compact reporting framework\u2014"
    "a proportional-bias\u2013aware slope, the CCC decomposition, the sampled "
    "pressure range and an explicit dynamic-response check\u2014that is usable "
    "in validation papers and in device-approval review. This framework is "
    "not an alternative to measurement-uncertainty analysis "
    + C.cite("gum2008") + "; it is a way to make the systematic part of that "
    "uncertainty visible when only paired device-reference measurements are "
    "available.")

add_para_with_refs(
    "Zeroing nevertheless remains indispensable at the bedside because these "
    "offsets are installation- and time-dependent physics rather than a "
    "factory-fixable device defect. The hydrostatic column depends on the "
    "height of the transducer relative to the phlebostatic axis (about "
    "7.5 mmHg per 10 cm) and changes whenever the patient or transducer is "
    "repositioned " + C.cite("gupta2025") + "; the atmospheric gauge "
    "reference drifts with weather and altitude; and electrical or thermal "
    "drift accumulates over time " + C.cite("mark1998", "mcghee2002") + ". "
    "Detection is not the same as correction: method-comparison analyses are "
    "retrospective and need paired reference measurements that are not "
    "available in real time, whereas zeroing removes a known, setup-specific "
    "offset a priori and without a reference. This also points to the design "
    "horizon: if the offset sources are engineered out of the hardware the "
    "need to zero disappears, leaving gain and dynamic response as the "
    "residual design and validation targets\u2014the same quantities our "
    "framework isolates.")

add_para_with_refs(
    "The contribution is therefore not a new blood pressure estimation "
    "algorithm. It is an instrumentation-and-measurement result about an "
    "existing calibration protocol: which error terms of a fluid-filled "
    "invasive pressure measurement chain zeroing can and cannot identify, "
    "which of the analyses used to accept such instruments recover the "
    "remaining terms, and what should consequently be reported. Section II "
    "places this question in the I&M literature, Section III gives the "
    "measurement model and the simulated and real-waveform experiments, "
    "Section IV reports the results, and Section V derives the reporting "
    "framework and the implications for sensor design.")

# ══════════════════════════════════════════════════════════════════
# 2. RELATED WORK IN INSTRUMENTATION AND MEASUREMENT
# ══════════════════════════════════════════════════════════════════
add_heading_styled("2. Related work in instrumentation and measurement", level=1)

add_para_with_refs(
    "Blood pressure instrumentation has a substantial literature in this "
    "journal, and it is against that work that our contribution should be "
    "placed. Balestrieri and Rapuano surveyed the instruments and methods used "
    "to calibrate oscillometric blood pressure devices and showed that "
    "calibration practice is dominated by static pressure references, with "
    "dynamic behaviour largely unaddressed " + C.cite("balestrieri2010") +
    ". Later work in the same venue has concentrated on estimation from the "
    "oscillometric or cuff signal: model-based mean arterial pressure "
    "estimation from simultaneous electrocardiogram and cuff measurements " +
    C.cite("forouzanfar2015") + ", a metrologically characterised arterial "
    "lumen-area model " + C.cite("koohi2017") + ", and an experimental "
    "characterisation of the cuff itself as a transducer " +
    C.cite("bogatu2021") + ". Alvarez Vazquez et al. quantified the "
    "uncertainty of consecutive auscultatory measurements " +
    C.cite("alvarez2022") + ", and Cosoli et al. showed for pressure-wave "
    "therapy devices that a full metrological characterisation has to include "
    "the waveform, not only scalar amplitude " + C.cite("cosoli2021") + ". "
    "What this body of work does not cover is the invasive, fluid-filled "
    "measurement chain and the specific consequence of its calibration "
    "protocol: zeroing corrects the offset term only, so the sensitivity and "
    "the dynamic transfer function remain unverified.")

add_para_with_refs(
    "Separating an offset error from a gain error is a standing problem in "
    "instrumentation, and the solutions differ by error type. Offset is "
    "typically handled at the interface: on-chip autocalibration cancels "
    "sensor offset in capacitive front ends " + C.cite("tirupathi2021") +
    ", and bias estimation with temperature compensation does the same for "
    "piezoresistive pressure sensors " + C.cite("ruan2021") + ". Gain, in "
    "contrast, requires a traceable reference: the histogram test for "
    "analogue-to-digital converters, for example, estimates gain and offset "
    "errors as separate parameters with separate precisions " +
    C.cite("alegria2007") + ". Bedside zeroing is functionally an offset-only "
    "autocalibration with no pressure reference attached, which is why the "
    "gain term is structurally unidentifiable from the zeroing procedure "
    "itself. Our study makes that asymmetry explicit and quantifies which "
    "reported analyses recover the gain term afterwards.")

add_para_with_refs(
    "For the frequency-dependent part of the error, dynamic calibration of "
    "pressure sensors has been addressed directly in this journal: Zakrzewski "
    "and Wróbel calibrated low-range silicon pressure sensors dynamically "
    "rather than statically " + C.cite("zakrzewski2002") + ", and dynamic "
    "sensor compensation has been implemented with analogue adaptive filters "
    + C.cite("jafaripanah2005") + " and analysed as an "
    "uncertainty-versus-complexity tradeoff " + C.cite("gubian2009") + ". The "
    "catheter\u2013transducer system is the clinical instance of exactly this "
    "problem, with the added constraint that the compensating element (tubing, "
    "bubbles, clots) is assembled at the bedside and changes during use, so "
    "the dynamic response must be re-checked in situ rather than calibrated "
    "once at manufacture. Finally, because acceptance in this field is a "
    "decision made under measurement uncertainty " +
    C.cite("gum2008", "morello2020") + ", the reporting framework we derive is "
    "aimed at the quantity that such decisions currently omit: the systematic "
    "scale term.")

# ══════════════════════════════════════════════════════════════════
# 3. METHODS
# ══════════════════════════════════════════════════════════════════
add_heading_styled("3. Methods", level=1)

add_heading_styled("3.1. Arterial pressure as DC plus AC components", level=2)
add_para_with_refs(
    rf"An arterial pressure waveform can be decomposed into a slowly varying DC "
    rf"level (mean arterial pressure plus any external offset) and a pulsatile "
    "alternating-current (AC) component driven by cardiac ejection. Pulse "
    rf"pressure ($PP = \mathrm{{SBP}} - \mathrm{{DBP}}$) is a pure AC "
    "quantity and is therefore independent of any additive DC offset but "
    rf"proportional to sensor gain (see Fig. {next_fig_num()}, which "
    "decomposes the arterial pressure signal into its DC and AC "
    rf"components). An offset shifts the baseline without changing $PP$, whereas a "
    "gain error scales the whole waveform and changes $PP$.")
add_figure(
    "Decomposition of the arterial pressure signal. (A) A DC offset shifts the "
    "baseline but leaves pulse pressure unchanged. (B) A gain error scales the "
    "entire waveform, so pulse pressure changes in proportion to the gain. "
    "Zeroing corrects the offset in (A) but cannot correct the gain error in (B).")

add_heading_styled("3.2. Statistical methods", level=2)
add_para_with_refs(
    "For each paired dataset we computed: (i) the minimal Bland\u2013Altman "
    "summary, comprising mean bias, 95% limits of agreement (mean bias \u00b1 1.96 SD) "
    "and percentage error " + C.cite("critchley1999") + "; (ii) the "
    "Bland\u2013Altman regression of the differences on the mean, whose slope "
    "tests for proportional bias " + C.cite("blandaltman1999") + "; (iii) "
    "Deming regression, which allows for error in both methods, with "
    "jackknife confidence intervals " + C.cite("linnet1990") + "; (iv) "
    "Passing\u2013Bablok non-parametric regression " +
    C.cite("passingbablok1983") + "; and (v) Lin\u2019s CCC " +
    C.cite("lin1989") + ".")

add_para_with_refs(
    "Lin\u2019s CCC (\u03c1c) decomposes as \u03c1c = r \u00d7 C_b, where r is "
    "Pearson\u2019s correlation (precision) and C_b is the bias-correction "
    "factor (accuracy) " + C.cite("lin2000") + ". C_b further decomposes as:")
add_eq(r"C_b = 2 / (v + 1/v + u^2)")
add_para_with_refs(
    rf"where $v = \sigma_{{\mathrm{{device}}}} / \sigma_{{\mathrm{{reference}}}}$ "
    rf"is the scale shift (the gain ratio) and "
    rf"$u = (\mu_{{\mathrm{{device}}}} - \mu_{{\mathrm{{reference}}}}) / "
    rf"\sqrt{{\sigma_{{\mathrm{{device}}}} \sigma_{{\mathrm{{reference}}}}}}$ "
    "is the location shift (offset). Zeroing drives $u$ toward zero but leaves "
    rf"$v$ unchanged; a residual gain error keeps $v \neq 1$ even after perfect zeroing.")

add_para_with_refs(
    rf"We used fixed a-priori detection rules, reported here so they cannot be "
    rf"chosen post hoc: the mean-bias summary flags an error if $|\mathrm{{mean\ bias}}| > "
    rf"{f1(P['bias_threshold'])}$ mmHg; the Bland-Altman regression flags if "
    "the slope 95% confidence interval (CI) excludes 0; Deming and "
    "Passing-Bablok flag if the slope 95% CI excludes 1; and the CCC "
    rf"scale shift flags if $|v - 1| > {f2(P['v_threshold'])}$. Strength of "
    "agreement was interpreted using published CCC criteria " +
    C.cite("mcbride2005") + ".")

add_heading_styled("3.3. Dynamic response and the fast-flush test", level=2)
add_para_with_refs(
    rf"The fluid-filled catheter-transducer system behaves as a second-order "
    rf"system characterised by a natural frequency $f_n$ and a damping "
    rf"coefficient $\zeta$ " + C.cite("gardner1981") + ". We modelled its "
    rf"transfer function $H(f) = 1 / [1 - (f/f_n)^2 + i \cdot 2\zeta(f/f_n)]$ "
    "and applied it to the Fourier harmonics of synthetic arterial waveforms. "
    rf"Under-damping (low $\zeta$, resonance near the arterial harmonics) causes "
    "systolic overshoot and $PP$ over-estimation; over-damping attenuates $PP$. "
    "Both are gain errors on the pulsatile signal that zeroing cannot correct, "
    "and both are quantified at the bedside by the fast-flush (square-wave) "
    "test " + C.cite("kleinman1992", "romagnoli2014") + ".")

add_heading_styled("3.4. Simulation design and reproducibility", level=2)
add_para_with_refs(
    rf"Static scenarios comprised $n = {P['n_static']}$ paired systolic pressures "
    rf"drawn uniformly over {P['sbp_low']}-{P['sbp_high']} mmHg with Gaussian "
    rf"measurement noise (SD = {f1(P['noise_sd'])} mmHg): S1 offset only "
    rf"(+{f1(P['offset_mmHg'])} mmHg, gain 1.0); S2 ideal zeroing (offset "
    rf"removed, gain 1.0); S3 uncompensated gain error (gain {f2(P['gain'])}); "
    "and S4 the same gain error with a compensating negative offset chosen so "
    "the mean difference is approximately zero. S4 is intentionally "
    "artificial: it is a worst-case contrivance that asks whether a mean-bias "
    "summary can be fooled by a chance cancellation of offset and gain, not a "
    "claim that real devices typically fail in this way. Dynamic scenarios "
    "passed synthetic waveforms through optimal, under-damped and over-damped "
    f"systems ({P['dyn_systems']['optimal']['fn']:.0f} Hz, "
    f"{P['dyn_systems']['optimal']['zeta']:.2f}; "
    f"{P['dyn_systems']['underdamped']['fn']:.0f} Hz, "
    f"{P['dyn_systems']['underdamped']['zeta']:.2f}; "
    f"{P['dyn_systems']['overdamped']['fn']:.0f} Hz, "
    f"{P['dyn_systems']['overdamped']['zeta']:.2f}). A range-dependence "
    "experiment sampled one fixed device (5% gain error) over pressure ranges "
    "of increasing width. The random seed, all parameters and the full pipeline "
    "(simulate -> analyse -> figures -> manuscript) are available in the "
    "public repository (https://github.com/bougtoir/abp_zero_calibration) so "
    "that a third party can regenerate every number, table and figure from a "
    "clean clone.")

add_heading_styled("3.5. Measurement uncertainty and sensitivity analysis", level=2)
add_para_with_refs(
    "Measurement uncertainty was treated following the Guide to the "
    "Expression of Uncertainty in Measurement " + C.cite("gum2008") + ". "
    "Random uncertainty comes from the Gaussian measurement noise ("
    rf"SD = {f1(P['noise_sd'])} mmHg) and from finite sample size; systematic "
    "uncertainty comes from the choice of dynamic-response parameters, the "
    "beat-detection algorithm on real waveforms and the a-priori detection "
    "thresholds. Bootstrap 95% confidence intervals are reported for all "
    "regression slopes. To test robustness we ran a threshold sweep on the "
    "masked-gain scenario and an (offset, gain) grid search. With mean-bias "
    "thresholds of 3, 5 and 10 mmHg the S4 mean bias remained inside the "
    "acceptance band, while the CCC scale shift $v$ flagged a gain error at "
    "all thresholds; with $v$ thresholds of 0.02, 0.05 and 0.10, S4 was "
    "flagged in every case. Across a grid of offsets (\u201320 to +20 mmHg) "
    "and gains (1.00 to 1.20), the mean-bias summary passed while $v$ flagged "
    "a gain error in "
    rf"{S['sensitivity']['grid']['masked_fraction']*100:.1f}% of "
    "combinations, defining the mean-bias blind spot quantitatively.")

add_heading_styled("3.6. Real-waveform validation with VitalDB", level=2)
add_para_with_refs(
    rf"To test whether the same gain/offset masking occurs in real waveforms, we "
    "selected a reproducible sample of cases with an invasive arterial pressure "
    rf"(SNUADC/ART) waveform from the VitalDB Open Dataset " + C.cite("vitaldb2022") +
    rf". Beat-by-beat systolic and diastolic pressures were extracted from a "
    rf"{RW.SEGMENT_SECONDS}-s intra-operative segment of each case, and the same "
    rf"four error models (offset only, ideal zeroing, uncompensated gain, and "
    "compensated gain) were applied to the real beat SBP values. The "
    "compensating offset in the gain-masked scenario (R4) was a single "
    "constant across all cases so that the overall mean bias was near zero "
    "while the gain-induced proportional bias survived; like S4, this is an "
    "intentional, artificial contrivance used to test whether the mean-bias "
    "summary can be masked. This real-data experiment is denoted R1-R4 and "
    "parallels the synthetic S1-S4 scenarios.")

add_para_with_refs(
    "The VitalDB dataset is publicly available and fully anonymised; no "
    "additional ethics approval was required for this secondary analysis. "
    "Use of artificial-intelligence tools: the simulation and analysis code, "
    "the figures, and drafts of the text were prepared with the assistance of "
    "an AI coding assistant (Devin; Cognition AI, San Francisco, California, "
    "USA). The authors reviewed and verified all code, numerical results and "
    "statements, and take full responsibility for the content of the article.")

# ══════════════════════════════════════════════════════════════════
# 3. RESULTS
# ══════════════════════════════════════════════════════════════════
add_heading_styled("4. Results", level=1)

add_heading_styled("4.1. Static scenarios", level=2)
add_para_with_refs(
    f"Concordance plots for the four static scenarios are shown in Fig. {next_fig_num()} and "
    f"the full metrics in Table 1. Ideal zeroing (S2) gave near-perfect "
    f"agreement (mean bias {signed(st['S2_zeroed_ideal']['bias'])} mmHg, "
    f"CCC {f3(st['S2_zeroed_ideal']['ccc'])}, $v$ "
    f"{f3(st['S2_zeroed_ideal']['v'])}). An uncompensated 10% gain error (S3) "
    f"was obvious on every analysis, including the mean bias "
    f"({signed(st['S3_gain_uncompensated']['bias'])} mmHg): gain error is not "
    "invisible to a Bland\u2013Altman analysis.")
add_figure(
    "Device-versus-reference concordance for the four static "
    "scenarios (dashed line = identity). Each panel shows the CCC, the CCC "
    "scale shift $v$, and the Bland\u2013Altman mean bias. S4 has a near-zero mean "
    "bias despite a 10% gain error.")
add_para("[TABLE 1]")

add_para_with_refs(
    f"The decisive case is S4, where a compensating offset makes the mean bias "
    f"only {signed(st['S4_gain_masked']['bias'])} mmHg, within the "
    f"\u00b1{f1(P['bias_threshold'])} mmHg acceptance band, so the minimal "
    "Bland\u2013Altman summary does not flag any problem. Every "
    "proportional-bias\u2013aware analysis nonetheless detects the hidden gain "
    f"error: the Bland\u2013Altman regression slope is "
    f"{f3(st['S4_gain_masked']['prop_slope'])} (95% CI "
    f"{ci(st['S4_gain_masked']['prop_slope_lo'], st['S4_gain_masked']['prop_slope_hi'])}), "
    f"the Deming slope {f3(st['S4_gain_masked']['deming_slope'])} (95% CI "
    f"{ci(st['S4_gain_masked']['deming_lo'], st['S4_gain_masked']['deming_hi'])}), "
    f"the Passing\u2013Bablok slope {f3(st['S4_gain_masked']['pb_slope'])} "
    f"(95% CI {ci(st['S4_gain_masked']['pb_lo'], st['S4_gain_masked']['pb_hi'])}), "
    f"and the CCC scale shift $v$ = {f3(st['S4_gain_masked']['v'])}. The "
    f"detection pattern across all scenarios is summarised in Fig. {next_fig_num()}, and the "
    f"difference-versus-mean plots for S2 and S4 in Fig. {next_fig_num()+1}.")
add_figure(
    "Which reported analysis detects the error in each scenario "
    "(green = detected, grey = missed). In S4 the mean-bias summary misses the "
    "gain error that every proportional-bias\u2013aware analysis detects.")
add_figure(
    "Bland\u2013Altman difference-versus-mean plots. In S2 the "
    "regression slope is flat; in S4 the slope is clearly positive despite a "
    "near-zero mean bias, revealing the masked proportional (gain) error.")

add_heading_styled("4.2. Dynamic-response scenarios", level=2)
add_para_with_refs(
    f"Dynamic-response metrics are given in Table 2 and illustrated in Fig. {next_fig_num()}. "
    f"The optimal system reproduced PP faithfully (PP ratio "
    f"{f2(dy['optimal_pp']['mean_ratio'])}). Under-damping produced systolic "
    f"overshoot and inflated PP by "
    f"{round((dy['underdamped_pp']['mean_ratio']-1)*100)}% (PP ratio "
    f"{f2(dy['underdamped_pp']['mean_ratio'])}, CCC scale shift $v$ = "
    f"{f2(dy['underdamped_pp']['v'])}); over-damping attenuated PP by "
    f"{round((1-dy['overdamped_pp']['mean_ratio'])*100)}% (PP ratio "
    f"{f2(dy['overdamped_pp']['mean_ratio'])}). These are gain errors on the "
    "pulsatile signal that survive zeroing. Because the distortion is "
    "frequency-dependent (it varies with heart rate rather than with pressure "
    "amplitude), it maps only partially onto the amplitude-proportional model "
    "underlying the static regression statistics, which is why it is best "
    "characterised directly by the fast-flush test parameters ($f_n$, \u03b6).")
add_para("[TABLE 2]")
add_figure(
    "Dynamic response of the catheter\u2013transducer system. (A) "
    "Frequency response of optimal, under-damped and over-damped systems with "
    "the arterial harmonics overlaid. (B) Example waveforms. (C) Measured "
    "versus true pulse pressure, with the mean PP ratio per system.")

add_heading_styled("4.3. Range-dependence of the CCC", level=2)
add_para_with_refs(
    f"For a single device with a fixed 5% gain error, the CCC rose from "
    f"{f2(rg['ccc'][0])} when sampled over a narrow pressure range "
    f"({int(rg['range_width'][0])} mmHg wide) to {f2(rg['ccc'][-1])} over a "
    f"wide range ({int(rg['range_width'][-1])} mmHg). The scale shift $v$ was "
    f"far less range-dependent than CCC and approached the true gain ratio as "
    f"the sampled range widened (Fig. {next_fig_num()}). The CCC "
    "therefore should be "
    "reported together with the sampled pressure range; the structural "
    "components ($C_b$, $v$) are more transportable across studies " +
    C.cite("nickerson1997") + ".")
add_figure(
    "Range-dependence of the CCC. For one fixed device, the CCC and $C_b$ "
    "increase as the sampled pressure range widens, whereas the scale shift "
    "$v$ is less range-dependent and approaches the true gain ratio "
    "(dotted line) at wider ranges.")

add_heading_styled("4.4. Real-waveform validation", level=2)
add_para_with_refs(
    f"The same four error models were applied to beat-by-beat invasive arterial "
    f"pressures from the VitalDB Open Dataset ($n = {P['n_real_cases']}$ cases, "
    f"$n = {P['n_real_beats_per_scenario']:,}$ paired beats per scenario). "
    "The pattern matched the synthetic data: a compensating "
    "offset made the mean bias effectively zero "
    f"({signed(rst['R4_gain_masked']['bias'])} mmHg), while the proportional-bias "
    "indicators remained elevated (CCC scale shift $v$ = "
    f"{f3(rst['R4_gain_masked']['v'])}, Deming slope "
    f"{f3(rst['R4_gain_masked']['deming_slope'])}, Passing\u2013Bablok slope "
    f"{f3(rst['R4_gain_masked']['pb_slope'])}). Table 3 gives the metrics for all "
    f"four real-data scenarios; Fig. {next_fig_num()} shows a representative 10-s "
    "waveform and the Bland\u2013Altman plot for R4.")
add_para("[TABLE 3]")
add_figure(
    "Real-waveform validation from the VitalDB Open Dataset. (A) "
    "A 10-s segment of the arterial pressure waveform (SNUADC/ART) with detected beats. "
    "(B) Bland\u2013Altman plot for the gain-masked scenario (R4) on real data, "
    "showing a near-zero mean bias with a clear proportional bias.")

add_heading_styled("4.5. Sensitivity and uncertainty", level=2)
add_para_with_refs(
    "A threshold sweep on the masked-gain scenario showed that the mean-bias "
    "summary passed every a-priori acceptance band (3, 5 and 10 mmHg), while "
    "the CCC scale shift $v$ and all regression-based proportional-bias tests "
    "flagged the gain error at every tested $v$ threshold (0.02, 0.05, 0.10). "
    "An (offset, gain) grid search over offsets \u201320 to +20 mmHg and gains "
    "1.00 to 1.20 confirmed a broad mean-bias blind spot: the mean-bias test "
    "passed while $v$ flagged the gain error in "
    f"{S['sensitivity']['grid']['masked_fraction']*100:.1f}% of the "
    "(offset, gain) combinations. This defines the numerical size of the "
    "reporting hazard and gives an uncertainty-aware context for the "
    "detection rule.")

# ══════════════════════════════════════════════════════════════════
# 4. DISCUSSION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("5. Discussion", level=1)
add_para_with_refs(
    "Our central finding is narrow and directly supported by the data: the "
    "mean-bias\u2013plus\u2013limits-of-agreement summary that dominates "
    "device-validation reporting can miss a clinically relevant gain error "
    "when a coincidental offset cancels its effect on the mean, whereas the "
    "Bland\u2013Altman difference-versus-mean regression " +
    C.cite("blandaltman1999") + ", Deming " + C.cite("linnet1990") +
    " and Passing\u2013Bablok " + C.cite("passingbablok1983") + " regression, "
    "and the CCC scale shift " + C.cite("lin2000") + " all detect it. This is "
    "a critique of common reporting practice, not of the Bland\u2013Altman "
    "method itself.")

add_heading_styled("5.1. Recommendations for validation reporting", level=2)
add_para_with_refs(
    "Validation studies of arterial pressure and derived monitors " +
    C.cite("kim2014", "joosten2017") + " should therefore report, in addition "
    "to mean bias and limits of agreement: (i) the Bland\u2013Altman regression "
    "slope with its CI (or, equivalently, a Deming or Passing\u2013Bablok "
    "slope); (ii) the CCC with its decomposition into r, C_b, u and v; and "
    "(iii) the sampled pressure range, because the CCC is range-dependent " +
    C.cite("nickerson1997", "barnhart2007") + ". Notably, C_b alone is "
    f"relatively insensitive to a pure gain error (in S4, C_b was "
    f"{f3(st['S4_gain_masked']['C_b'])} despite v = "
    f"{f3(st['S4_gain_masked']['v'])}); the scale shift v should be reported "
    "explicitly. These additions require only standard regression output and "
    "make the systematic part of the measurement uncertainty visible "
    "to regulators and clinicians " + C.cite("odor2017") +
    ", distinguishing offset-corrected agreement from genuine gain accuracy.")
add_para_with_refs(
    "Relative to the uncertainty budgets reported for non-invasive blood "
    "pressure measurement " + C.cite("alvarez2022") + ", which characterise "
    "the repeatability of a measurement procedure, the quantity we recommend "
    "adding is systematic rather than random: v is a scale term that does not "
    "shrink with repetition and that a limits-of-agreement statement can hide "
    "when an offset partially cancels it. Reporting it explicitly keeps the "
    "accept/reject decision consistent with the uncertainty on which it is "
    "based " + C.cite("gum2008", "morello2020") + ".")

add_heading_styled("5.2. Dynamic response is a distinct, clinical gain error", level=2)
add_para_with_refs(
    "The dynamic-response error is specific to fluid-filled systems and is "
    "routinely encountered at the bedside as under-damping (air bubbles, long "
    "compliant tubing) or over-damping (clots, kinks) " +
    C.cite("gardner1981", "romagnoli2014") + ". Because it is "
    "frequency-dependent, it is not fully captured by static "
    "method-comparison statistics and is best assessed directly with the "
    "fast-flush test, from which f_n and \u03b6 are read " +
    C.cite("kleinman1992") + ". We therefore recommend that a fast-flush "
    "dynamic-response check accompany any accuracy statement for a "
    "fluid-filled arterial line; pulse pressure is the sensitive readout, "
    "because it is proportional to gain but independent of offset.")
add_para_with_refs(
    "In instrumentation terms this is the in-situ counterpart of dynamic "
    "sensor calibration and compensation " +
    C.cite("zakrzewski2002", "jafaripanah2005", "gubian2009") + ". Those "
    "methods characterise or invert a transfer function that is fixed by the "
    "device; here the second-order system is completed by tubing, fluid and "
    "air that are assembled at the bedside and change during use, so f_n and "
    "\u03b6 have to be re-estimated from the measurement chain in place. The "
    "fast-flush test is attractive precisely because it supplies that estimate "
    "from a step response without a pressure reference, and Cosoli et al. make "
    "the same point for therapeutic pressure devices: waveform-level "
    "characterisation is not optional once the quantity of interest is "
    "pulsatile " + C.cite("cosoli2021") + ".")

add_heading_styled("5.3. Implications for sensor design", level=2)
add_para_with_refs(
    "The reason zeroing is still performed today is that it corrects a "
    "setup-specific offset in real time, a role that no retrospective "
    "method-comparison statistic can fill. This also points to the way "
    "forward: because zeroing addresses only the operational offset problem, "
    "designing the offset sources out of the hardware removes the need to zero "
    "at all, leaving gain and dynamic response as the residual design and "
    "validation problems. The same division of labour is visible in sensor "
    "interface design, where offset is cancelled on chip " +
    C.cite("tirupathi2021") + " or estimated jointly with temperature "
    "effects " + C.cite("ruan2021") + ", while gain accuracy still has to be "
    "established against a reference, as in ADC gain and offset error testing "
    + C.cite("alegria2007") + ". Zeroing occupies the first role only.")
add_para_with_refs(
    "The offset that zeroing corrects can also be removed by design. "
    "Catheter-tip micro-electro-mechanical systems (MEMS) sensors abolish the "
    "hydrostatic column " + C.cite("hasenkamp2012", "song2020") + "; absolute "
    "sensors with barometric compensation remove the atmospheric reference; "
    "and self-calibrating MEMS references limit drift " + C.cite("kang2022") +
    ". High-fidelity pressure wires already demonstrate accurate catheter-based "
    "pressure measurement " + C.cite("scalia2023") + ". With offset removed by "
    "design and gain verified by accurate PP reproduction, the residual "
    "systematic error is expressed entirely in v, giving a concrete design "
    "target (v \u2248 1, C_b \u2265 0.99 without calibration) " +
    C.cite("mcbride2005") + ". Modern piezoresistive MEMS sensors achieve "
    "non-linearity well below 0.1% of full scale " + C.cite("barlian2009") +
    ", supporting the assumption that gain verified over the pulsatile range "
    "generalises across the physiological range.")

add_heading_styled("5.4. Extension to derived haemodynamic monitors", level=2)
add_para_with_refs(
    "The offset-versus-gain distinction extends to derived monitors whose "
    "auto-calibration routines re-optimise a setpoint (an offset correction) "
    "without correcting the gain of the pressure- or "
    "impedance-to-flow conversion " +
    C.cite("chatterjee2009", "ameloot2015", "squara2007", "manecke2005") +
    ". Reporting the scale shift v for these devices would make their "
    "dependence on calibration explicit.")

add_heading_styled("5.5. Limitations", level=2)
add_para_with_refs(
    "This is a simulation study; the data are synthetic and chosen to isolate "
    "specific error structures, and they are not a substitute for a "
    "prospective clinical comparison against an invasive reference of stated "
    "precision " + C.cite("cecconi2009") + ". The masked-gain scenarios (S4 "
    "and R4) are intentionally artificial: they test whether a summary metric "
    "can be fooled by a cancellation of offset and gain, not whether devices "
    "typically fail in this way. The static model assumes sensor linearity, "
    "the dynamic model is a single second-order approximation, and the "
    "measurement-uncertainty budget is limited to the components we could "
    "propagate from the stated simulation parameters. The value of the work is "
    "to make explicit, and reproducibly quantify, which reported analyses "
    "detect a residual gain error, a prelude to rather than a replacement for "
    "empirical validation.")

# ══════════════════════════════════════════════════════════════════
# 6. CONCLUSION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("6. Conclusion", level=1)
add_para_with_refs(
    "Zero calibration corrects offset but not gain, and a residual scale error "
    "can persist after perfect zeroing.")
add_para_with_refs(
    "Dynamic-response error is a distinct, frequency-dependent gain error that "
    "also survives zeroing and is diagnosed at the bedside by the fast-flush "
    "test.")
add_para_with_refs(
    "Read on its own, a mean-bias\u2013plus\u2013limits-of-agreement summary "
    "can miss such a gain error when an offset masks it, whereas Bland\u2013"
    "Altman regression, Deming and Passing\u2013Bablok regression, and the CCC "
    "scale shift all detect it. The message for clinicians and manufacturers "
    "is not to abandon Bland\u2013Altman but to use it with its regression step "
    "and these complementary analyses.")
add_para_with_refs(
    "We recommend that arterial pressure validation studies, and device-"
    "approval evaluations, report a proportional-bias\u2013aware analysis, the "
    "CCC decomposition with the sampled pressure range, and an explicit "
    "dynamic-response check, so that offset-corrected agreement is not mistaken "
    "for gain accuracy.")
add_para_with_refs(
    "Because zeroing addresses only the operational offset, designing the "
    "offset sources out of the hardware would make zeroing unnecessary and "
    "leave gain and dynamic response as the residual targets; expressing the "
    "remaining systematic error as the scale shift v gives a concrete design "
    "goal (v \u2248 1 without calibration) for the next generation of "
    "self-calibrating arterial pressure sensors.")

# ══════════════════════════════════════════════════════════════════
# DECLARATIONS (conflicts of interest and funding are stated on the title
# page, as required by IEEE TIM author guidelines)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Acknowledgements", level=1)
add_para("[To be completed by the authors, or state \u201cnone\u201d.]")
add_heading_styled("Data availability", level=1)
add_para(
    "Replication code, parameter files, and the generated data used to produce "
    "every number, table and figure are available in the public repository "
    "https://github.com/bougtoir/abp_zero_calibration. The real-waveform "
    "validation uses the VitalDB Open Dataset, which is publicly available at "
    "https://api.vitaldb.net/.")

doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# REFERENCES (numbered in order of first appearance; in-text as [n])
# ══════════════════════════════════════════════════════════════════
add_heading_styled("References", level=1)
missing = C.check_all_cited()
for idx, ref in enumerate(C.ordered_references(), start=1):
    p = doc.add_paragraph()
    run = p.add_run(f"[{idx}] {ref}")
    run.font.name = "Times New Roman"
    run.font.size = Pt(9)
    p.paragraph_format.space_after = Pt(2)
    p.paragraph_format.line_spacing = 1.0
    p.paragraph_format.first_line_indent = Cm(-0.7)
    p.paragraph_format.left_indent = Cm(0.7)

doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# TABLE 1 — static metrics (built from summary; no vertical rules)
# ══════════════════════════════════════════════════════════════════
add_para("Table 1. Method-comparison metrics for the four static scenarios "
         f"(n = {P['n_static']} paired measurements each).",
         bold=True, italic=True)

t1_headers = ["Scenario", "Mean bias\n(mmHg)", "95% LoA\n(mmHg)", "PE (%)",
              "BA reg. slope\n(95% CI)", "Deming slope\n(95% CI)",
              "P\u2013B slope\n(95% CI)", "CCC", "C_b", "v"]
scen_names = {
    "S1_offset_only": "S1 offset only",
    "S2_zeroed_ideal": "S2 zeroed (ideal)",
    "S3_gain_uncompensated": "S3 gain error",
    "S4_gain_masked": "S4 gain masked",
}
table = doc.add_table(rows=1 + len(scen_names), cols=len(t1_headers))
DATA_TABLES.append(table)
horizontal_borders(table); set_table_width(table, width_in=3.25)
for i, h in enumerate(t1_headers):
    cell = table.rows[0].cells[i]
    cell.text = h
    for p in cell.paragraphs:
        for r in p.runs:
            r.bold = True; r.font.size = Pt(8); r.font.name = "Times New Roman"

for row_idx, (key, label) in enumerate(scen_names.items(), start=1):
    d = st[key]
    row = [
        label,
        signed(d["bias"]),
        f"{d['loa_lower']:.1f} to {d['loa_upper']:.1f}",
        f1(d["pe"]),
        f"{d['prop_slope']:.3f}\n({d['prop_slope_lo']:.3f}, {d['prop_slope_hi']:.3f})",
        f"{d['deming_slope']:.3f}\n({d['deming_lo']:.3f}, {d['deming_hi']:.3f})",
        f"{d['pb_slope']:.3f}\n({d['pb_lo']:.3f}, {d['pb_hi']:.3f})",
        f3(d["ccc"]), f3(d["C_b"]), f3(d["v"]),
    ]
    for col_idx, txt in enumerate(row):
        cell = table.rows[row_idx].cells[col_idx]
        cell.text = txt
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(8); r.font.name = "Times New Roman"

add_para(
    "BA = Bland\u2013Altman; CI = confidence interval; LoA = limits of agreement; "
    "PE = percentage error; P\u2013B = Passing\u2013Bablok; CCC = concordance "
    "correlation coefficient; C_b = bias-correction factor; v = scale shift. "
    "S4 has a near-zero mean bias yet a clearly non-zero regression, Deming and "
    "Passing\u2013Bablok slope and v > 1, i.e. a gain error hidden from the "
    "mean-bias summary.", italic=True)
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# TABLE 2 — dynamic metrics (built from summary; no vertical rules)
# ══════════════════════════════════════════════════════════════════
add_para("Table 2. Dynamic-response metrics for pulse pressure (PP) and "
         "systolic pressure (SBP).", bold=True, italic=True)

t2_headers = ["System (f_n, \u03b6)", "PP ratio", "PP mean bias\n(mmHg)",
              "CCC (PP)", "v (PP)", "SBP mean bias\n(mmHg)"]
_ds = P["dyn_systems"]
dyn_rows = {
    "optimal": f"Optimal ({f1(_ds['optimal']['fn'])} Hz, {f2(_ds['optimal']['zeta'])})",
    "underdamped": f"Underdamped ({f1(_ds['underdamped']['fn'])} Hz, {f2(_ds['underdamped']['zeta'])})",
    "overdamped": f"Overdamped ({f1(_ds['overdamped']['fn'])} Hz, {f2(_ds['overdamped']['zeta'])})",
}
table2 = doc.add_table(rows=1 + len(dyn_rows), cols=len(t2_headers))
DATA_TABLES.append(table2)
horizontal_borders(table2); set_table_width(table2, width_in=3.25)
for i, h in enumerate(t2_headers):
    cell = table2.rows[0].cells[i]
    cell.text = h
    for p in cell.paragraphs:
        for r in p.runs:
            r.bold = True; r.font.size = Pt(8); r.font.name = "Times New Roman"

for row_idx, (key, label) in enumerate(dyn_rows.items(), start=1):
    pp = dy[f"{key}_pp"]; sbp = dy[f"{key}_sbp"]
    row = [label, f2(pp["mean_ratio"]), signed(pp["bias"]),
           f3(pp["ccc"]), f3(pp["v"]), signed(sbp["bias"])]
    for col_idx, txt in enumerate(row):
        cell = table2.rows[row_idx].cells[col_idx]
        cell.text = txt
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(8); r.font.name = "Times New Roman"

add_para(
    "PP ratio = mean(measured PP / true PP); f_n = natural frequency; "
    "\u03b6 = damping coefficient. Under-damping inflates and over-damping "
    "attenuates pulse pressure; the mean arterial (DC) level is preserved, so "
    "zeroing does not correct these errors.", italic=True)
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# TABLE 3 — real-waveform metrics (VitalDB)
# ══════════════════════════════════════════════════════════════════
add_para(f"Table 3. Real-waveform method-comparison metrics from the VitalDB Open Dataset ({P['n_real_cases']} cases; n = {P['n_real_beats_per_scenario']:,} paired beats per scenario).",  
         bold=True, italic=True)

t3_headers = ["Scenario", "n", "Mean bias\n(mmHg)", "95% LoA\n(mmHg)", "PE (%)",
              "BA reg. slope\n(95% CI)", "Deming slope\n(95% CI)",
              "P\u2013B slope\n(95% CI)", "CCC", "C_b", "v"]
real_scenarios = {
    "R1_offset_only": "R1 offset only",
    "R2_zeroed_ideal": "R2 zeroed (ideal)",
    "R3_gain_uncompensated": "R3 gain error",
    "R4_gain_masked": "R4 gain masked",
}
table3 = doc.add_table(rows=1 + len(real_scenarios), cols=len(t3_headers))
DATA_TABLES.append(table3)
horizontal_borders(table3); set_table_width(table3, width_in=3.25)
for i, h in enumerate(t3_headers):
    cell = table3.rows[0].cells[i]
    cell.text = h
    for p in cell.paragraphs:
        for r in p.runs:
            r.bold = True; r.font.size = Pt(8); r.font.name = "Times New Roman"

for row_idx, (key, label) in enumerate(real_scenarios.items(), start=1):
    d = rst[key]
    row = [
        label,
        str(d["n"]),
        signed(d["bias"]),
        f"{d['loa_lower']:.1f} to {d['loa_upper']:.1f}",
        f1(d["pe"]),
        f"{d['prop_slope']:.3f}\n({d['prop_slope_lo']:.3f}, {d['prop_slope_hi']:.3f})",
        f"{d['deming_slope']:.3f}\n({d['deming_lo']:.3f}, {d['deming_hi']:.3f})",
        f"{d['pb_slope']:.3f}\n({d['pb_lo']:.3f}, {d['pb_hi']:.3f})",
        f3(d["ccc"]), f3(d["C_b"]), f3(d["v"]),
    ]
    for col_idx, txt in enumerate(row):
        cell = table3.rows[row_idx].cells[col_idx]
        cell.text = txt
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(8); r.font.name = "Times New Roman"

add_para(
    "BA = Bland\u2013Altman; CI = confidence interval; LoA = limits of agreement; "
    "PE = percentage error; P\u2013B = Passing\u2013Bablok; CCC = concordance "
    "correlation coefficient; C_b = bias-correction factor; v = scale shift. "
    "R4 has a near-zero mean bias with elevated v and regression slopes, "
    "reproducing the masked-gain pattern found in synthetic scenario S4.", italic=True)
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# MOVE TABLES INLINE (insert at [TABLE N] placeholders)
# ══════════════════════════════════════════════════════════════════
def move_tables_inline():
    """Move each table, its caption and its footnote to the placeholder in the body."""
    placeholders = {}
    headings = {}
    captions = {}
    footnotes = {}
    for p in doc.paragraphs:
        t = p.text.strip()
        if t.startswith("[TABLE ") and t.endswith("]"):
            placeholders[t] = p
        elif t in ("Table 1", "Table 2", "Table 3"):
            headings[t] = p
        elif t.startswith(("Table 1.", "Table 2.", "Table 3.")):
            captions[t.split(".")[0]] = p
        elif t.startswith("BA = ") or t.startswith("PP ratio = "):
            footnotes[t] = p
    for idx, table in enumerate(DATA_TABLES, start=1):
        marker = f"[TABLE {idx}]"
        table_key = f"Table {idx}"
        ph = placeholders.get(marker)
        cap = captions.get(table_key)
        if not ph or not cap:
            continue
        if table_key in headings:
            ph._p.addprevious(headings[table_key]._p)
        ph._p.addprevious(cap._p)
        ph._p.addnext(table._tbl)
        # attach the matching footnote (first footnote for Table 1/3; PP for Table 2)
        if table_key in ("Table 1", "Table 3"):
            fn = next((f for txt, f in footnotes.items() if txt.startswith("BA = ")), None)
        else:
            fn = next((f for txt, f in footnotes.items() if txt.startswith("PP ratio = ")), None)
        if fn:
            table._tbl.addnext(fn._p)
            footnotes.pop(fn.text.strip(), None)
        ph._element.getparent().remove(ph._element)

move_tables_inline()

doc.save(OUTPATH)
print(f"English TIM manuscript saved: {OUTPATH}")
print(f"References cited: {len(C.order)} / {len(REFDB)} in database")
print(f"Figures inserted: {FIGURE_NUM}")
if missing:
    print(f"WARNING: uncited references in database: {missing}")
