@echo off
cd /d "%~dp0"
setlocal enabledelayedexpansion

echo.
echo ========================================================
echo   anesthesia-record v0.2 Setup (Real-time GUI)
echo ========================================================
echo.

REM --- Python チェック ---
REM py launcher を優先、なければ python
set PYCMD=
py -3 --version >nul 2>&1
if %errorlevel% equ 0 (
    set PYCMD=py -3
    goto :pyfound
)
where python >nul 2>&1
if %errorlevel% equ 0 (
    set PYCMD=python
    goto :pyfound
)
echo [エラー] Python が見つかりません。
echo https://www.python.org/downloads/ からインストールしてください。
echo インストール時に Add Python to PATH にチェックを入れてください。
pause
exit /b 1

:pyfound
for /f "tokens=*" %%i in ('%PYCMD% --version 2^>^&1') do set PYVER=%%i
echo Python: %PYVER%
echo.

REM --- プロジェクト用 venv 作成 ---
if not exist .venv (
    echo プロジェクト用仮想環境を作成中...
    %PYCMD% -m venv .venv
    if %errorlevel% neq 0 (
        echo [エラー] venv の作成に失敗しました。
        pause
        exit /b 1
    )
)
call .venv\Scripts\activate.bat
echo venv: .venv
echo.

REM --- バイタルデータ取込ソフト選択 ---
echo --------------------------------------------------------
echo   バイタルデータの取込方法を選択してください
echo --------------------------------------------------------
echo.
echo   [1] VSCapture - GE/Philips モニター直結
echo.
echo       対応モニター:
echo         - GE CARESCAPE B650 / B850 / B450
echo         - GE Solar 8000M / 8000i
echo         - Philips IntelliVue MX800 / MX700 / MP70 / MP60
echo         - Philips IntelliVue X3
echo       出力形式: CSV
echo       特徴: モニターにLAN接続し直接バイタルを記録
echo              HL7/GE Solar protocol
echo.
echo   [2] VitalRecorder - 多機種対応
echo.
echo       対応モニター:
echo         - GE CARESCAPE 全シリーズ
echo         - Philips IntelliVue 全シリーズ
echo         - Nihon Kohden BSM / CSM シリーズ
echo         - Mindray BeneVision N シリーズ
echo         - Drager Infinity / Perseus
echo         - Masimo Root / Radical-7
echo         - Medtronic BIS / NicoletOne
echo         - その他 HL7 対応モニター全般
echo       出力形式: .vital / CSV
echo       特徴: vitaldb.net 提供の汎用レコーダ
echo              高サンプリングレート波形対応
echo              vitaldb package for .vital
echo.
echo   [3] 外部モニタビデオキャプチャ（推奨）
echo.
echo       対応機器:
echo         - GE CARESCAPE B650 / B850 / B450（DVI/HDMI出力）
echo         - その他 DVI/HDMI/DisplayPort/VGA 外部出力のモニター全般
echo       特徴: UVC HDMIキャプチャボード + OpenCV/RapidOCR で数値読取
echo              ネットワーク/HL7ライセンス不要
echo              BIS 行あり/なし、トレンド画面でも動作
echo.
echo --------------------------------------------------------
echo.

set /p CHOICE="選択 (1, 2 または 3): "

if "%CHOICE%"=="1" (
    set SOURCE=vscapture
    set SOURCE_LABEL=VSCapture
    echo.
    echo VSCapture を選択しました。
) else if "%CHOICE%"=="2" (
    set SOURCE=vitalrecorder
    set SOURCE_LABEL=VitalRecorder
    echo.
    echo VitalRecorder を選択しました。
) else if "%CHOICE%"=="3" (
    set SOURCE=video
    set SOURCE_LABEL=外部モニタビデオキャプチャ
    echo.
    echo 外部モニタビデオキャプチャを選択しました。
) else (
    echo.
    echo [エラー] 1, 2 または 3 を入力してください。
    pause
    exit /b 1
)

echo.
echo --------------------------------------------------------
echo   依存ライブラリをインストール中...
echo --------------------------------------------------------
echo.

python -m ensurepip --upgrade >nul 2>&1
python -m pip install --upgrade pip >nul 2>&1
python -m pip install "PyYAML>=6.0" "matplotlib>=3.7" numpy scipy
if %errorlevel% neq 0 (
    echo [エラー] 基本ライブラリのインストールに失敗しました。
    pause
    exit /b 1
)

if "%SOURCE%"=="vitalrecorder" (
    echo.
    echo vitaldb パッケージをインストール中...
    python -m pip install "vitaldb>=1.4"
    if %errorlevel% neq 0 (
        echo [警告] vitaldb のインストールに失敗しました。
        echo .vital ファイルの読込は利用できませんが、CSV は使用可能です。
    )
)

if "%SOURCE%"=="video" (
    echo.
    echo ビデオキャプチャ用ライブラリをインストール中...
    python -m pip install "opencv-python>=4.8" "Pillow>=10.0" "rapidocr-onnxruntime>=1.4"
    if %errorlevel% neq 0 (
        echo [エラー] ビデオキャプチャ用ライブラリのインストールに失敗しました。
        pause
        exit /b 1
    )
)

echo.
echo --------------------------------------------------------
echo   デフォルト設定を生成中...
echo --------------------------------------------------------
echo.

REM --- config.yaml 生成 ---
if "%SOURCE%"=="vscapture" (
    set VITALS_SOURCE=vscapture_csv
) else if "%SOURCE%"=="vitalrecorder" (
    set VITALS_SOURCE=vitalrecorder_csv
) else (
    set VITALS_SOURCE=video_monitor
)

echo # anesthesia-record default config> config.yaml
echo # Auto-generated by setup.bat>> config.yaml
echo:>> config.yaml
echo vitals:>> config.yaml
echo   source: !VITALS_SOURCE!>> config.yaml
echo   clock_offset_sec: 0.0>> config.yaml
echo   interval_sec: 1.0>> config.yaml
echo:>> config.yaml
echo chart:>> config.yaml
echo   title: "anesthesia record">> config.yaml
echo   show_floating_latest: true>> config.yaml
echo   latest_panel_loc: "upper right">> config.yaml
echo   ce_horizon_min: 60>> config.yaml
echo:>> config.yaml
echo output:>> config.yaml
echo   format: png>> config.yaml
echo   dpi: 150>> config.yaml

echo 設定ファイルを生成しました: config.yaml
echo   バイタルソース: %SOURCE_LABEL%
echo.

REM --- PyInstaller ビルド ---
echo --------------------------------------------------------
echo   実行ファイルをビルドしますか？
echo --------------------------------------------------------
echo.
set /p BUILD="実行ファイル(.exe)をビルドする？ (y/n): "

if /i "%BUILD%"=="y" (
    echo.
    echo PyInstaller をインストール中...
    python -m pip install pyinstaller
    echo.
    echo ビルド中... （数分かかります）
    pyinstaller --onefile --add-data "data;data" --name anesthesia_record run_gui.py
    if %errorlevel% neq 0 (
        echo [エラー] ビルドに失敗しました。
        pause
        exit /b 1
    )
    echo.
    echo dist\anesthesia_record.exe が生成されました。
)

echo.
echo ========================================================
echo   セットアップ完了！
echo ========================================================
echo.
echo   選択ソース: %SOURCE_LABEL%
echo   設定ファイル: config.yaml
echo.
echo   使い方:
echo     python run_gui.py           リアルタイムGUIを起動
echo     python main.py case.yaml    バッチモードでチャート生成
echo     python main.py --demo       デモチャート生成
echo     python -m pytest -q         テスト実行
if "%SOURCE%"=="video" (
echo.
echo   ビデオキャプチャ:
echo     python -m anesthesia_record.monitor_video --config paperchart\b650_video.yaml --device 0
echo     1回だけ撮影＋ROI確認:
echo       python -m anesthesia_record.monitor_video --config paperchart\b650_video.yaml --device 0 --overlay roi.png
)
if /i "%BUILD%"=="y" (
echo     dist\anesthesia_record.exe  実行ファイルで実行
)
echo.
echo   詳細は docs\manual.md を参照してください。
echo ========================================================
echo.
pause
