#!/usr/bin/env python3
"""
Prepare final, manuscript-aligned figure files for the IEEE Sensors Journal submission.

Inputs are taken from `results_in_engineering_submission/rie_figures/` (the
reproducible figure assets generated by the public DVS pipeline). The script:

1. Copies the required PNGs into `ieee_figures/` so `create_ieee_docx.py` and
   `create_ieee_supporting_files.py` have a self-contained local source.
2. Creates `editorial_figures/` with sequentially numbered filenames
   (Figure_01...Figure_07 plus Supplementary Figure S1) for separate
   Editorial-Manager upload.
"""

import shutil
import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUT_DIR = SCRIPT_DIR / 'ieee_figures'
EDITORIAL_DIR = SCRIPT_DIR / 'editorial_figures'
SRC_DIR = SCRIPT_DIR.parent / 'results_in_engineering_submission' / 'rie_figures'

# Order matches the IEEE manuscript after fig6 was moved to supplementary.
FIGURE_MAP = [
    ('fig1_schematic.png', 'Figure_01_schematic.png'),
    ('fig2_optimal_rho.png', 'Figure_02_optimal_rho.png'),
    ('fig3_pipeline_en.png', 'Figure_03_pipeline.png'),
    ('fig4_sr_curves.png', 'Figure_04_sr_curves.png'),
    ('fig5_detection_and_roc.png', 'Figure_05_detection_and_roc.png'),
    ('fig7_evaluation_and_application.png', 'Figure_06_evaluation_and_application.png'),
    ('fig8_proof_of_concept.png', 'Figure_07_proof_of_concept.png'),
]
SUPPLEMENTARY_MAP = [
    ('fig6_a5_simulation.png', 'Figure_S1_a5_simulation.png'),
    ('supplementary_fig_per_recording.png', 'Figure_S2_per_recording.png'),
]


def _remove_existing(path: Path):
    """Remove a file or symlink so we can replace it with a directory."""
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def copy_figures():
    if not SRC_DIR.exists():
        raise FileNotFoundError(f"Source figure directory not found: {SRC_DIR}")

    _remove_existing(OUT_DIR)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for src_name, _ in FIGURE_MAP + SUPPLEMENTARY_MAP:
        src = SRC_DIR / src_name
        if not src.exists():
            raise FileNotFoundError(f"Missing source figure: {src}")
        shutil.copy2(src, OUT_DIR / src_name)
        print(f"Copied {src_name}")


def prepare_editorial_figures():
    """Create a second copy with sequential figure numbers for journal upload."""
    _remove_existing(EDITORIAL_DIR)
    EDITORIAL_DIR.mkdir(parents=True, exist_ok=True)

    for src_name, dst_name in FIGURE_MAP + SUPPLEMENTARY_MAP:
        shutil.copy2(OUT_DIR / src_name, EDITORIAL_DIR / dst_name)

    key = {
        'source_to_editorial': {
            src: dst for src, dst in FIGURE_MAP + SUPPLEMENTARY_MAP
        },
    }
    (EDITORIAL_DIR / 'figure_key.json').write_text(
        json.dumps(key, indent=2) + '\n', encoding='utf-8'
    )
    print(f"Prepared {len(FIGURE_MAP) + len(SUPPLEMENTARY_MAP)} editorial figures in {EDITORIAL_DIR}")


def main():
    copy_figures()
    prepare_editorial_figures()
    print('IEEE figure preparation complete.')


if __name__ == '__main__':
    main()
