"""Build a data-driven parameters.yaml for the cancer-screening burden simulation.

All cancer incidence values are derived from public National Cancer Center of Japan
(Cancer Statistics in Japan, 2016-2023) and Japanese 2023 population data in the same
file. Diagnostic capacity values are derived from the MHLW 2023 Medical Facility Survey
(05sisetu05.xlsx). Test performance, pathway probabilities, and the "available for new
cancer workups" capacity share remain scenario assumptions, documented in the comments.

Run this script before simulate.py:
    python3 prepare_parameters.py
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd
import yaml

from specialist_capacity import (
    compute_primary_care_capacity_inputs,
    compute_specialist_capacity_inputs,
    load_specialist_counts,
    read_ndb_outpatient_patients,
)


DATA_DIR = Path(__file__).parent / "data"
PARAMS_OUT = Path(__file__).parent / "parameters.yaml"

POP_FILE = DATA_DIR / "cancer_incidenceNCR_2016-2023E.xlsx"
CAPACITY_FILE = DATA_DIR / "05sisetu05.xlsx"

# Population in 2023 (used to convert counts to per-100k rates).
POPULATION_2023 = 124_351_000

# Share of the total national exam volume assumed to be available for new
# cancer workups generated by a DTC screening wave. This is a scenario
# assumption; the base value is the same as the original model.
AVAILABLE_CANCER_SHARE = 0.20

# Age columns shared by the incidence "rate" and "pop" sheets.
AGE_COLS = [
    "0-4 yrs.",
    "5-9 yrs.",
    "10-14 yrs.",
    "15-19 yrs.",
    "20-24 yrs.",
    "25-29 yrs.",
    "30-34 yrs.",
    "35-39 yrs.",
    "40-44 yrs.",
    "45-49 yrs.",
    "50-54 yrs.",
    "55-59 yrs.",
    "60-64 yrs.",
    "65-69 yrs.",
    "70-74 yrs.",
    "75-79 yrs.",
    "80-84 yrs.",
    "85-89 yrs.",
    "90-94 yrs.",
    "95-99 yrs.",
    "100+ yrs.",
]

CHILD_TEEN_COLS = ["0-4 yrs.", "5-9 yrs.", "10-14 yrs.", "15-19 yrs."]
ADULT_COLS = [c for c in AGE_COLS if c not in CHILD_TEEN_COLS]


@lru_cache(maxsize=None)
def load_pop(sex: str, year: int = 2023) -> pd.Series:
    pop = pd.read_excel(POP_FILE, sheet_name="pop", header=0)
    row = pop[
        (pop["Population"] == "All (including foreigners)")
        & (pop["Sex"] == sex)
        & (pop["Calendar year"] == year)
    ]
    if row.empty:
        raise ValueError(f"No population row found for sex={sex}, year={year}")
    return row.iloc[0]


@lru_cache(maxsize=None)
def load_incidence_rate(sex: str, site: str, year: int = 2023) -> pd.Series:
    rate = pd.read_excel(POP_FILE, sheet_name="rate", header=0)
    sub = rate[
        (rate["Year at diagnosis"] == year) & (rate["Sex"] == sex) & (rate["Site"] == site)
    ]
    if sub.empty:
        raise ValueError(f"No incidence rate found for {sex=}, {site=}, {year=}")
    return sub.iloc[0]


def per100k_total(count: float) -> float:
    """Convert an absolute count to cases per 100,000 total Japanese population."""
    return count / POPULATION_2023 * 100_000.0


def adult_incidence_per100k_total(sex: str, site: str) -> float:
    """Compute adult (20+) incidence per 100,000 total population.

    This is used as a proxy for the point prevalence of screen-detectable
    cancers in the DTC-screened cohort. Because point prevalence of
    undiagnosed cancers is likely lower than annual incidence, this tends to
    overestimate true positives and PPV and underestimate FP/TP ratios.
    """
    pop_row = load_pop(sex)
    rate_row = load_incidence_rate(sex, site)
    adult_cases = 0.0
    for col in ADULT_COLS:
        rate = rate_row[col]
        if pd.isna(rate) or rate == "-":
            continue
        adult_cases += float(rate) * float(pop_row[col]) / 100_000.0
    return per100k_total(adult_cases)


def compute_age_specific_incidence(sex: str, site: str) -> pd.DataFrame:
    """Return a DataFrame with age-group incidence rates (per 100k in that age group)."""
    pop_row = load_pop(sex)
    rate_row = load_incidence_rate(sex, site)
    rows = []
    for col in AGE_COLS:
        rate = rate_row[col]
        if pd.isna(rate) or rate == "-":
            continue
        rows.append({"age_group": col, "incidence_per_100k": float(rate)})
    return pd.DataFrame(rows)


def compute_capacity() -> Dict[str, float]:
    """Compute annual diagnostic exam counts per 100k from MHLW facility survey.

    The survey reports one-month patient counts for September 2023. Annualising with
    *12 gives a total national volume; we then apply AVAILABLE_CANCER_SHARE to reflect
    the portion that can be reallocated to cancer workups from a single DTC wave.
    """
    xl = pd.ExcelFile(CAPACITY_FILE)
    # Sheet 11 (0-indexed) contains facility counts; sheet 12 contains patient counts.
    hosp = xl.parse(10, header=None)
    clinic = xl.parse(11, header=None)

    def monthly_patients(df: pd.DataFrame, codes: List[str], modality: str) -> float:
        total = 0.0
        found = False
        for code in codes:
            row = df[df[2].astype(str).str.strip() == code]
            if row.empty:
                continue
            found = True
            val = row.iloc[0, 9]
            try:
                total += float(val)
            except Exception as exc:
                raise ValueError(
                    f"Could not convert monthly patient count for {modality} code {code!r}: {val!r}"
                ) from exc
        return total, found

    ct_hosp, ct_hosp_found = monthly_patients(hosp, ["13", "14", "15", "16", "17"], "CT")
    ct_clinic, ct_clinic_found = monthly_patients(clinic, ["13", "14", "15", "16", "17"], "CT")
    if not (ct_hosp_found or ct_clinic_found):
        raise ValueError("No CT monthly patient counts found in hospital or clinic tables")
    ct_monthly = ct_hosp + ct_clinic

    mri_hosp, mri_hosp_found = monthly_patients(hosp, ["18", "19", "20"], "MRI")
    mri_clinic, mri_clinic_found = monthly_patients(clinic, ["18", "19", "20"], "MRI")
    if not (mri_hosp_found or mri_clinic_found):
        raise ValueError("No MRI monthly patient counts found in hospital or clinic tables")
    mri_monthly = mri_hosp + mri_clinic

    gastro_hosp, gastro_hosp_found = monthly_patients(hosp, ["03"], "upper-GI endoscopy")
    gastro_clinic, gastro_clinic_found = monthly_patients(clinic, ["03"], "upper-GI endoscopy")
    if not (gastro_hosp_found or gastro_clinic_found):
        raise ValueError("No upper-GI endoscopy monthly patient counts found")
    gastro_monthly = gastro_hosp + gastro_clinic

    colon_hosp, colon_hosp_found = monthly_patients(hosp, ["04"], "lower-GI endoscopy")
    colon_clinic, colon_clinic_found = monthly_patients(clinic, ["04"], "lower-GI endoscopy")
    if not (colon_hosp_found or colon_clinic_found):
        raise ValueError("No lower-GI endoscopy monthly patient counts found")
    colon_monthly = colon_hosp + colon_clinic
    endoscopy_monthly = gastro_monthly + colon_monthly

    def per100k_annual(monthly: float) -> float:
        return monthly * 12 / POPULATION_2023 * 100_000.0 * AVAILABLE_CANCER_SHARE

    # Specialist capacity is not reported by the facility survey. Derive it from
    # NDB Open Data outpatient patient counts and JMSB specialist counts.
    ndb_outpatient = read_ndb_outpatient_patients()
    specialist_counts = load_specialist_counts()
    specialist_inputs = compute_specialist_capacity_inputs(
        ndb_outpatient, specialist_counts, AVAILABLE_CANCER_SHARE, POPULATION_2023
    )
    primary_care_inputs = compute_primary_care_capacity_inputs(
        ndb_outpatient, specialist_counts, AVAILABLE_CANCER_SHARE, POPULATION_2023
    )

    return {
        "ct_exams_per_year": per100k_annual(ct_monthly),
        "mri_exams_per_year": per100k_annual(mri_monthly),
        "endoscopy_exams_per_year": per100k_annual(endoscopy_monthly),
        "specialist_visits_per_year": specialist_inputs["specialist_visits_per_year"],
        "specialist_capacity_note": (
            f"Derived from NDB Open Data first/revisit outpatient patient counts "
            f"({ndb_outpatient['first_visit_patients']:,.0f} + {ndb_outpatient['revisit_patients']:,.0f}) "
            f"and {specialist_inputs['relevant_specialists']:,.0f} cancer-relevant JMSB specialists; "
            f"{AVAILABLE_CANCER_SHARE:.0%} share assumed available for new cancer workups."
        ),
        "primary_care_visits_per_year": primary_care_inputs["primary_care_visits_per_year"],
        "primary_care_capacity_note": (
            f"Derived from NDB Open Data first/revisit outpatient patient counts "
            f"({ndb_outpatient['first_visit_patients']:,.0f} + {ndb_outpatient['revisit_patients']:,.0f}) "
            f"and {primary_care_inputs['primary_care_specialists']:,.0f} primary-care-relevant JMSB specialists "
            f"(internal medicine and general practice); {AVAILABLE_CANCER_SHARE:.0%} share assumed available "
            f"for new cancer workups."
        ),
    }


def build_cancer_list() -> List[Dict[str, Any]]:
    """Return cancer blocks with data-driven prevalence and documented assumptions."""
    cancers: List[Dict[str, Any]] = [
        {
            "name": "Gastric",
            "site": "Stomach",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Stomach"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.30, "mri": 0.10, "endoscopy": 0.90, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 4.0,
            "fp_additional_visits": 1.5,
        },
        {
            "name": "Colorectal",
            "site": "Colon/rectum",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Colon/rectum"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.30, "mri": 0.05, "endoscopy": 0.95, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 4.0,
            "fp_additional_visits": 1.5,
        },
        {
            "name": "Lung",
            "site": "Lung, trachea",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Lung, trachea"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.90, "mri": 0.15, "endoscopy": 0.05, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 5.0,
            "fp_additional_visits": 2.0,
        },
        {
            "name": "Breast",
            "site": "Breast",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Breast"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.10, "mri": 0.30, "endoscopy": 0.05, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 4.0,
            "fp_additional_visits": 1.5,
        },
        {
            "name": "Prostate",
            "site": "Prostate",
            "sex": "Male",
            "prevalence_per_100k": adult_incidence_per100k_total("Male", "Prostate"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.10, "mri": 0.40, "endoscopy": 0.05, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 3.0,
            "fp_additional_visits": 1.5,
        },
        {
            "name": "Liver",
            "site": "Liver",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Liver"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.40, "mri": 0.30, "endoscopy": 0.10, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 4.0,
            "fp_additional_visits": 1.5,
        },
        {
            "name": "Pancreatic",
            "site": "Pancreas",
            "sex": "Both",
            "prevalence_per_100k": adult_incidence_per100k_total("Both", "Pancreas"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.60, "mri": 0.30, "endoscopy": 0.20, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 5.0,
            "fp_additional_visits": 2.0,
        },
        {
            "name": "Ovarian",
            "site": "Ovary",
            "sex": "Female",
            "prevalence_per_100k": adult_incidence_per100k_total("Female", "Ovary"),
            "sensitivity": 0.70,
            "specificity": 0.99,
            "pathway": {"ct": 0.40, "mri": 0.50, "endoscopy": 0.05, "specialist": 1.00, "primary_care": 1.00},
            "tp_additional_visits": 5.0,
            "fp_additional_visits": 2.0,
        },
    ]
    return cancers


def build_parameters() -> Dict[str, Any]:
    cancers = build_cancer_list()
    capacity = compute_capacity()

    params: Dict[str, Any] = {
        "simulation": {
            "screened_population": 100_000,
            "follow_up_rates": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
            "random_seed": 42,
        },
        "capacity": capacity,
        "specificity_sweep": {
            "follow_up_rate": 0.5,
            "specificity_values": [0.950, 0.980, 0.990, 0.995, 0.999],
        },
        "cancers": cancers,
        "data_sources": {
            "cancer_incidence": {
                "source": "National Cancer Center of Japan, Cancer Statistics in Japan 2016-2023",
                "url": "https://ganjoho.jp/reg_stat/statistics/data/dl/en.html",
                "file": str(POP_FILE.name),
                "note": "Adult (20+) incidence rates for 2023 are used as a proxy for the point prevalence of screen-detectable cancers. Because point prevalence of undiagnosed cancers is usually lower than annual incidence, this tends to overestimate true positives and PPV and underestimate FP/TP ratios.",
            },
            "population": {
                "source": "National Cancer Center of Japan, population by age/sex 2023",
                "url": "https://ganjoho.jp/reg_stat/statistics/data/dl/en.html",
                "file": str(POP_FILE.name),
            },
            "diagnostic_capacity": {
                "source": "Ministry of Health, Labour and Welfare, 2023 Medical Facility Survey (Static/Dynamic), 05sisetu05.xlsx",
                "url": "https://www.mhlw.go.jp/toukei/saikin/hw/iryosd/23/",
                "file": str(CAPACITY_FILE.name),
                "note": "September 2023 one-month patient counts are annualised (x12) and multiplied by AVAILABLE_CANCER_SHARE (20%) to estimate the cancer-diagnostic capacity available to a DTC screening wave.",
            },
            "test_performance": {
                "source": [
                    "Kahwati LC, Avenarius M, Brouwer L, et al. Blood-Based Tests for Multiple Cancer Screening: A Systematic Review. AHRQ Publication No. 25-EHC033. Rockville (MD): Agency for Healthcare Research and Quality; 2025. https://doi.org/10.23970/AHRQEPCSRMULTIPLE",
                    "LeeVan E, Pinsky P. Predictive Performance of Cell-Free Nucleic Acid-Based Multi-Cancer Early Detection Tests: A Systematic Review. Clin Chem. 2024;70(1):90-101. https://doi.org/10.1093/clinchem/hvad134",
                ],
                "note": "Base-case sensitivity 0.70 is near the MCED review median (0.73); specificity 0.99 is within the reported range (0.657-1.0). Per-cancer values are uniform scenario assumptions; the specificity_sweep explores the effect of overall test accuracy.",
            },
            "real_world_ppv": {
                "source": "Nagamachi S et al., nationwide PET/CT facility survey on N-NOSE-triggered examinations (2024). https://jcpet.jp/2024/10/senchu-chosa.html",
                "note": "Observed cancer discovery rate after N-NOSE high-risk was ~2% overall and <1% for the 15 target cancers; company-claimed 11.7% PPV is disputed by the original survey authors.",
            },
        },
        "assumptions": {
            "available_for_cancer_share": AVAILABLE_CANCER_SHARE,
            "pathway_note": "Pathway probabilities and additional-visit counts are expert-assumption scenario values based on standard diagnostic guidelines, not empirical data.",
            "prevalence_proxy_note": "Point prevalence of undiagnosed screen-detectable cancers is not publicly reported; adult incidence is used as a proxy. Because point prevalence is likely lower than annual incidence, this may overestimate true positives and PPV and underestimate FP/TP ratios.",
        },
    }
    return params


def main() -> None:
    params = build_parameters()
    with open(PARAMS_OUT, "w", encoding="utf-8") as f:
        yaml.safe_dump(params, f, sort_keys=False, allow_unicode=True, default_flow_style=False)
    print(f"Wrote {PARAMS_OUT.resolve()}")


if __name__ == "__main__":
    main()
