#!/usr/bin/env python3
"""Create English cover letter for Health Policy submission."""
import json
import os
from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from string import Template

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'documents', 'Health_Policy')
os.makedirs(OUTPUT_DIR, exist_ok=True)

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
with open(os.path.join(REPO_ROOT, 'output', 'ijhpm_results.json')) as f:
    R = json.load(f)


def fmt(x, d=1):
    if x is None or (isinstance(x, float) and x != x):
        return 'NA'
    return f'{x:.{d}f}'


FLAT = {
    'n_areas': R['metadata']['n_areas'],
    'n_prefectures': R['metadata']['n_prefectures'],
    'fiscal_year': R['metadata'].get('fiscal_year', 2022),
    'L008_cv': fmt(R['codes']['L008']['overall']['cv']),
    'L002_cv': fmt(R['codes']['L002']['overall']['cv']),
    'L008_ml_icc': fmt(R['codes']['L008']['multilevel']['icc_null'], 3),
    'L008_ml_icc_pct': fmt(R['codes']['L008']['multilevel']['icc_null'] * 100, 1),
    'L008_ml_within_pct': fmt(100 * (1 - R['codes']['L008']['multilevel']['icc_null']), 1),
    'L008_ml_r2': fmt(R['codes']['L008']['multilevel']['marginal_r2'], 3),
    'L008_ml_r2_pct': fmt(R['codes']['L008']['multilevel']['marginal_r2'] * 100, 1),
    'L008_d': fmt(R['empirical_bayes']['L008']['raw_cohens_d'], 2),
}

# Use the word/reference counts generated by create_health_policy_en.py
META_PATH = os.path.join(OUTPUT_DIR, 'health_policy_submission_metadata.json')
if os.path.exists(META_PATH):
    with open(META_PATH) as f:
        META = json.load(f)
else:
    # Fallback for standalone runs: sensible defaults that will be overwritten
    # when the full build pipeline is executed.
    META = {
        'body_word_count': 3000,
        'abstract_word_count': 250,
        'n_tables': 2,
        'n_figures': 2,
        'n_references': 21,
    }

FLAT.update({
    'body_word_count': str(int(META.get('body_word_count', 3000))),
    'abstract_word_count': str(int(META.get('abstract_word_count', 250))),
    'n_tables': str(int(META.get('n_tables', 2))),
    'n_figures': str(int(META.get('n_figures', 2))),
    'n_references': str(int(META.get('n_references', 21))),
})

doc = Document()
for section in doc.sections:
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.top_margin = Cm(2.54)
    section.bottom_margin = Cm(2.54)
    section.left_margin = Cm(2.54)
    section.right_margin = Cm(2.54)

style = doc.styles['Normal']
style.font.name = 'Times New Roman'
style.font.size = Pt(12)
style.paragraph_format.line_spacing = 1.5
style.paragraph_format.space_after = Pt(6)


def add_para(text, italic=False, bold=False, align=None):
    p = doc.add_paragraph()
    if align is not None:
        p.alignment = align
    run = p.add_run(Template(text).substitute(FLAT))
    run.font.name = 'Times New Roman'
    run.font.size = Pt(12)
    run.italic = italic
    run.bold = bold
    return p


add_para("[Corresponding author name]", italic=True, align=WD_ALIGN_PARAGRAPH.RIGHT)
add_para("[Affiliation]", italic=True, align=WD_ALIGN_PARAGRAPH.RIGHT)
add_para("[Postal address]", italic=True, align=WD_ALIGN_PARAGRAPH.RIGHT)
add_para("[Email]  |  [Telephone]", italic=True, align=WD_ALIGN_PARAGRAPH.RIGHT)
add_para("[Date]", italic=True, align=WD_ALIGN_PARAGRAPH.RIGHT)
doc.add_paragraph()

add_para("The Editor-in-Chief")
add_para("Health Policy")
add_para("Elsevier")
doc.add_paragraph()

add_para("Dear Editor,")
doc.add_paragraph()

add_para(
    "I am pleased to submit for your consideration the enclosed original "
    "research article entitled \"Regional variation in anaesthesia practice "
    "in Japan under universal health coverage: structural determinants and "
    "claims-audit sensitivity\" for possible publication in Health Policy.")

add_para(
    "The manuscript addresses a clinically relevant question in perioperative "
    "medicine: when routine administrative claims data show large geographic "
    "variation in anaesthesia technique, does this reflect real differences in "
    "service delivery, or is it an artefact of differential coding and auditing? "
    "Japan's uniform national fee schedule combined with prefecture-specific "
    "claims auditing provides a natural experiment for separating these "
    "explanations. Using multilevel modelling and a series of pre-specified "
    "sensitivity and robustness analyses, we show that the observed variation is "
    "substantial and appears to reflect structural access factors -- notably proximity to university hospitals -- "
    "rather than an audit artefact. The findings have direct implications for "
    "neuraxial anaesthesia access, postoperative pain management and workforce "
    "policy. We therefore believe the paper is a strong fit for Health Policy's "
    "interest in health-system design, equity and the use of administrative "
    "data to inform policy.")

add_para(
    "Key findings: We studied all ${n_areas} secondary medical areas of Japan "
    "nested within ${n_prefectures} prefectures. Coefficients of variation for "
    "age- and sex-standardised claim ratios ranged from ${L008_cv}% (general "
    "anaesthesia) to ${L002_cv}% (epidural anaesthesia). For general "
    "anaesthesia, only ${L008_ml_icc_pct}% of variance lay between prefectures -- "
    "where audit policy differs -- while ${L008_ml_within_pct}% occurred within "
    "prefectures where audit policy is uniform. University hospital presence "
    "was associated with the largest proportional reduction in total variance "
    "for general anaesthesia (${L008_ml_r2_pct}%) and was positive in all "
    "${n_prefectures} prefectures, with a large effect size (Cohen's d "
    "${L008_d}). Sensitivity and robustness analyses—within-prefecture paired "
    "comparisons, covariate adjustment, empirical Bayes shrinkage, log-transformation, "
    "and audit-sensitivity checks (maximum audit-rate impact, code correlations and a "
    "combined general/spinal measure)—all pointed away from differential auditing as the "
    "main explanation; empirical Bayes shrinkage confirmed robustness to "
    "low-volume instability.")

add_para(
    "The manuscript is original, has not been previously published and is not "
    "under consideration for publication elsewhere. All authors have read and "
    "approved the submitted manuscript and have agreed to its submission to "
    "Health Policy. The study used publicly available "
    "aggregate data only; ethics committee approval was not required under the "
    "Japanese Ethical Guidelines for Medical and Biological Research Involving "
    "Human Subjects (2021 revision). The reporting follows the STROBE checklist "
    "for cross-sectional studies, which is uploaded as supplementary material, "
    "and a Highlights file is provided as required.")

add_para(
    "Statistical analysis: the lead author, who has training in clinical "
    "epidemiology and statistics, performed the analyses and takes full "
    "responsibility for them. No professional statistician outside the author "
    "list was consulted. We declare that Devin (Cognition AI) was used as a "
    "coding assistant to support data processing, statistical modelling, "
    "geographic visualisation and manuscript formatting; all scientific "
    "interpretation, methodological decisions and wording of scientific claims "
    "were made by the human authors, who take full responsibility for the "
    "integrity and accuracy of the work.")

add_para(
    "The manuscript is within Health Policy limits for a full-length article "
    "(main text approximately ${body_word_count} words; structured abstract "
    "${abstract_word_count} words, within 250 words; ${n_tables} tables and "
    "${n_figures} figures combined; ${n_references} references). We have "
    "uploaded a separate title page, the anonymised main manuscript, a Highlights "
    "file, separate editable tables and figures, and the STROBE checklist.")

add_para(
    "We believe our work will be of substantive interest to the Journal's "
    "international audience of anaesthesiologists, perioperative-care "
    "specialists and health-system researchers, and we look forward to the "
    "reviewers' comments. Please do not hesitate to contact me if any further "
    "information is required.")

doc.add_paragraph()
add_para("Yours sincerely,")
doc.add_paragraph()
add_para("[Signature]")
add_para("[Corresponding author name], on behalf of all authors", italic=True)

out = os.path.join(OUTPUT_DIR, 'cover_letter_Health_Policy_EN.docx')
doc.save(out)
print(f"Saved: {out}")
