"""Stage 1a freeze: write results/stage1_original_hypothesis_report.md.

Documents the original confirmatory prediction and its falsification, reading
numbers from results/tables/*.csv (no hard-coded statistics).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import ROOT, TABLES


def main() -> None:
    beta = pd.read_csv(
        TABLES / "stage1_beta_summary.csv", names=["metric", "value"], header=0
    ).set_index("metric")["value"]
    sens = pd.read_csv(TABLES / "stage1_sampling_sensitivity.csv")

    md = f"""# Stage 1a — Original confirmatory hypothesis (FROZEN)

This report freezes the confirmatory result before any exploratory
reverse-signal analyses. Generated by `analysis/98_stage1a_freeze_report.py`
from `results/tables/*.csv`.

## Original prediction (confirmatory)

H1: Δβ = β_predator − β_herbivore > 0
(predator communities turn over geographically faster than herbivore
communities)

## Observed

| Metric | Δβ | bootstrap 95% CI | P(Δβ>0) |
|---|---|---|---|
| Simpson | {beta['delta_beta_simpson_overall']:.3f} | [{beta['delta_beta_simpson_boot_lo']:.3f}, {beta['delta_beta_simpson_boot_hi']:.3f}] | {beta['delta_beta_simpson_boot_p_gt0']:.3f} |
| Sorensen | {beta['delta_beta_sorensen_overall']:.3f} | [{beta['delta_beta_sorensen_boot_lo']:.3f}, {beta['delta_beta_sorensen_boot_hi']:.3f}] | {beta['delta_beta_sorensen_boot_p_gt0']:.3f} |

Sampling-correction sensitivity (`stage1_sampling_sensitivity.csv`):

{sens.to_markdown(index=False)}

## Verdict

**The original directional hypothesis is FALSIFIED.** The bootstrap interval
excludes zero and the observed direction is opposite to the prediction.

## Unexpected reverse signal

A large, statistically clear signal in the opposite direction
(Δβ < 0: predator turnover < herbivore turnover) was observed. Per protocol,
no post hoc one-sided p-value for Δβ < 0 is computed on this dataset as
confirmatory evidence. The biological interpretation of the reverse
direction is **exploratory** until independently validated (Stage 1c).

Two-sided statement that remains legitimate: guild turnover differed
significantly and the direction was opposite to prediction.
"""
    out = ROOT / "results" / "stage1_original_hypothesis_report.md"
    out.write_text(md)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
